In [2]:
import numpy as np
from PIL import Image

# ===================================================
# Q1: Basic NumPy Array
# ===================================================

# (a) Reverse array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Q1 (a) Reversed:", arr[::-1])

# (b) Flatten array (two methods)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Q1 (b) Flatten using flatten():", array1.flatten())
print("Q1 (b) Flatten using ravel():", array1.ravel())

# (c) Compare arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Q1 (c) Arrays equal?:", np.array_equal(arr1, arr2))

# (d) Most frequent values & indices
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
for name, arr in {"x": x, "y": y}.items():
    vals, counts = np.unique(arr, return_counts=True)
    max_val = vals[np.argmax(counts)]
    indices = np.where(arr == max_val)[0]
    print(f"Q1 (d) {name}: most frequent={max_val}, indices={indices}")

# (e) Matrix sums
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Q1 (e) Sum of all:", gfg.sum())
print("Q1 (e) Row-wise sum:", gfg.sum(axis=1))
print("Q1 (e) Column-wise sum:", gfg.sum(axis=0))

# (f) Matrix operations
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
print("Q1 (f) Diagonal sum:", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("Q1 (f) Eigenvalues:", eig_vals)
print("Q1 (f) Eigenvectors:\n", eig_vecs)
print("Q1 (f) Inverse:\n", np.linalg.inv(n_array))
print("Q1 (f) Determinant:", np.linalg.det(n_array))

# (g) Matrix multiplication & covariance
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
print("Q1 (g) p1*q1:\n", np.dot(p1, q1))
print("Q1 (g) Covariance of p1:\n", np.cov(p1.T))
print("Q1 (g) Covariance of q1:\n", np.cov(q1.T))

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print("Q1 (g) p2*q2:\n", np.dot(p2, q2))
print("Q1 (g) Covariance of p2:\n", np.cov(p2.T))
print("Q1 (g) Covariance of q2:\n", np.cov(q2.T))
print("Q1 (g) Covariance between p2 & q2 (flattened):\n", np.cov(p2.flatten(), q2.flatten()))

# (h) Products
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("Q1 (h) Inner:\n", np.inner(x, y))
print("Q1 (h) Outer:\n", np.outer(x, y))
print("Q1 (h) Cartesian product:\n", np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2))


# ===================================================
# Q2: Mathematics & Statistics
# ===================================================

# (a) Array calculations
array = np.array([[1, -2, 3], [-4, 5, -6]])
print("Q2 (a) Absolute:\n", np.abs(array))
print("Q2 (a) Percentiles (flat):", np.percentile(array, [25, 50, 75]))
print("Q2 (a) Percentiles (col):\n", np.percentile(array, [25, 50, 75], axis=0))
print("Q2 (a) Percentiles (row):\n", np.percentile(array, [25, 50, 75], axis=1))
print("Q2 (a) Mean (flat):", np.mean(array))
print("Q2 (a) Median (flat):", np.median(array))
print("Q2 (a) Std (flat):", np.std(array))
print("Q2 (a) Mean (col):", np.mean(array, axis=0))
print("Q2 (a) Median (col):", np.median(array, axis=0))
print("Q2 (a) Std (col):", np.std(array, axis=0))
print("Q2 (a) Mean (row):", np.mean(array, axis=1))
print("Q2 (a) Median (row):", np.median(array, axis=1))
print("Q2 (a) Std (row):", np.std(array, axis=1))

# (b) Floor, ceil, trunc, round
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Q2 (b) Floor:", np.floor(a))
print("Q2 (b) Ceil:", np.ceil(a))
print("Q2 (b) Trunc:", np.trunc(a))
print("Q2 (b) Round:", np.round(a))


# ===================================================
# Q3: Searching & Sorting
# ===================================================

# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Q3 (a) Sorted:", np.sort(array))
print("Q3 (a) Indices sorted:", np.argsort(array))
print("Q3 (a) 4 smallest:", np.sort(array)[:4])
print("Q3 (a) 5 largest:", np.sort(array)[-5:])

# (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
ints = array[array == array.astype(int)]
floats = array[array != array.astype(int)]
print("Q3 (b) Integers:", ints)
print("Q3 (b) Floats:", floats)


# ===================================================
# Q4: Image to Array
# ===================================================

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:  # Grayscale
        np.savetxt("grayscale_img.txt", arr, fmt="%d")
    else:  # RGB
        np.savetxt("rgb_img.txt", arr.reshape(-1, arr.shape[-1]), fmt="%d")
    return arr

def load_txt_array(file_path):
    return np.loadtxt(file_path, dtype=int)



Q1 (a) Reversed: [5 4 6 3 2 1]
Q1 (b) Flatten using flatten(): [1 2 3 2 4 5 1 2 3]
Q1 (b) Flatten using ravel(): [1 2 3 2 4 5 1 2 3]
Q1 (c) Arrays equal?: True
Q1 (d) x: most frequent=1, indices=[0 5 7 8 9]
Q1 (d) y: most frequent=1, indices=[0 1 2]
Q1 (e) Sum of all: 45
Q1 (e) Row-wise sum: [[14]
 [16]
 [15]]
Q1 (e) Column-wise sum: [[20  9 16]]
Q1 (f) Diagonal sum: 176
Q1 (f) Eigenvalues: [98.16835147 28.097044   49.73460452]
Q1 (f) Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Q1 (f) Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Q1 (f) Determinant: 137180.0000000001
Q1 (g) p1*q1:
 [[16 19]
 [26 31]]
Q1 (g) Covariance of p1:
 [[0.5 0.5]
 [0.5 0.5]]
Q1 (g) Covariance of q1:
 [[2. 2.]
 [2. 2.]]
Q1 (g) p2*q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Q1 (g) Covariance of p2:
 [[2.33333333 2.33333333]
 [2.33333333 2.33333333]